# Generated by Django 4.1 on 2023-02-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userData",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
                (
                    "referral_code_used",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "referral_code_generated",
                    models.CharField(max_length=12, unique=True),
                ),
                ("number_of_referred", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
