# Generated by Django 4.1 on 2023-02-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referal_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="number_of_referred",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="referral_code_used",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
